BIN = lp.exe

SRC_DIR = src

OBJ = $(SRC_DIR)/stack.obj $(SRC_DIR)/parser.obj $(SRC_DIR)/simplex.obj $(SRC_DIR)/queue.obj $(SRC_DIR)/main.obj

$(SRC_DIR)/%.obj: $(SRC_DIR)/%.c
    cl /c /Fo$@ $<

$(BIN): $(OBJ)
    cl $(OBJ) /Fe$(BIN)

clean:
    del /F /Q $(SRC_DIR)\*.obj $(BIN)